# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=250)),
                ('fa_icon', models.CharField(max_length=12)),
                ('bg_color', models.CharField(max_length=12)),
            ],
        ),
    ]
